rm -r magus_decompose/__pycache__
rm -r magus_working_dir
rm -r magus_decompose/magus_align/__pycache__
rm -r magus_decompose/magus_helpers/__pycache__
rm -r magus_decompose/magus_tasks/__pycache__
rm -r magus_decompose/magus_tools/__pycache__
rm -r magus_decompose/__pycache__
rm -r MAGUS/magus_align/__pycache__
rm -r MAGUS/magus_helpers/__pycache__
rm -r MAGUS/magus_tasks/__pycache__
rm -r MAGUS/magus_tools/__pycache__
rm -r tmp